-- =============================================================================
-- MIGRATION 001: CORE SCHEMA, EXTENSIONS, ENUMS, TABLES, CONSTRAINTS & INDEXES
-- Project: Notre Dame College (NDC) Alumni Platform
-- Target: Supabase PostgreSQL (Designed for 100,000+ Alumni Scale)
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. EXTENSIONS
-- -----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;

SET search_path = public, extensions;

-- -----------------------------------------------------------------------------
-- 2. ENUM TYPES (Idempotent Creation)
-- -----------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE public.user_role AS ENUM ('member', 'moderator', 'admin');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.verification_status AS ENUM ('unverified', 'pending_vouch', 'verified');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.verification_method AS ENUM ('two_vouches', 'id_card_upload', 'souvenir_photo', 'admin_verified');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.verification_doc_type AS ENUM ('id_card', 'nid_card', 'hsc_slip', 'souvenir');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.request_review_status AS ENUM ('pending', 'approved', 'rejected', 'verified', 'declined');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.blood_group_type AS ENUM ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.blood_donor_availability AS ENUM ('available', 'on_cooldown', 'unavailable');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.blood_alert_preference AS ENUM ('all_urgent', 'same_area_only', 'critical_only', 'paused');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.blood_emergency_level AS ENUM ('critical', 'urgent', 'standard');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.blood_request_status AS ENUM (
    'Pending Verification',
    'Active',
    'Donor Found',
    'Donation Confirmed',
    'Fulfilled',
    'Cancelled',
    'Expired'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.blood_contact_method AS ENUM (
    'Portal Secure Coordination',
    'Hospital Blood Bank Desk',
    'Batch Coordinator Relay',
    'Attendant Emergency Line'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.blood_response_status AS ENUM ('offered', 'accepted', 'confirmed_donated', 'declined');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.post_category_type AS ENUM (
    'General Update',
    'Tech & Innovation',
    'Professional Insights',
    'Reunion',
    'Achievement'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.notification_type AS ENUM ('like', 'comment', 'post', 'system', 'blood', 'verification');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.gallery_category_type AS ENUM (
    'reunion',
    'academic',
    'campus',
    'convocation',
    'sports',
    'cultural',
    'all'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.notice_category_type AS ENUM ('Membership', 'Reunion', 'Scholarship', 'General', 'AGM');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.academic_stream_type AS ENUM ('Science', 'Humanities', 'Business Studies');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- -----------------------------------------------------------------------------
-- 3. TABLES & CONSTRAINTS
-- -----------------------------------------------------------------------------

-- 3.0 academic_stream_groups (Reference / Configuration Table)
-- Validates (academic_stream, academic_group) pairs across alumni and verification
-- tables. Allows group_code IS NULL for stream-level capacity metadata (e.g.,
-- Science expected_group_count = 17 before official Science group codes are added).
CREATE TABLE IF NOT EXISTS public.academic_stream_groups (
  id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stream public.academic_stream_type NOT NULL,
  group_code VARCHAR(32) NULL CHECK (group_code IS NULL OR char_length(trim(group_code)) BETWEEN 1 AND 32),
  expected_group_count SMALLINT NOT NULL CHECK (expected_group_count BETWEEN 1 AND 50),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_academic_stream_group_pair UNIQUE (stream, group_code)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_academic_stream_null_group_metadata
  ON public.academic_stream_groups (stream)
  WHERE group_code IS NULL;

-- 3.1 batches
-- Unverified institutional metadata fields (session, hsc_year, special_note,
-- representative_name, estimated_total) are nullable so Migration 004 never has
-- to seed fabricated institutional facts.
CREATE TABLE IF NOT EXISTS public.batches (
  batch_year SMALLINT PRIMARY KEY CHECK (batch_year BETWEEN 1 AND 150),
  session VARCHAR(64) NULL UNIQUE,
  hsc_year SMALLINT NULL CHECK (hsc_year IS NULL OR (hsc_year BETWEEN 1949 AND 2100)),
  special_note TEXT NULL,
  representative_name TEXT NULL,
  representative_profile_id BIGINT NULL, -- FK added after alumni_profiles is created
  registered_count INTEGER NOT NULL DEFAULT 0 CHECK (registered_count >= 0),
  estimated_total INTEGER NULL CHECK (estimated_total IS NULL OR estimated_total >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3.2 alumni_profiles
-- Note: Passwords are NEVER stored here. Authentication is handled by auth.users.
-- Sensitive contact fields (email, phone, whatsapp, fb_link, college_roll) are
-- protected by column-level privilege revocations, RLS, and controlled RPCs in 002 & 003.
CREATE TABLE IF NOT EXISTS public.alumni_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10000 INCREMENT BY 1) PRIMARY KEY,
  auth_user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.user_role NOT NULL DEFAULT 'member',
  full_name TEXT NOT NULL CHECK (char_length(trim(full_name)) BETWEEN 2 AND 150),
  avatar_url TEXT NOT NULL DEFAULT '/ndc-logo.png',
  cover_url TEXT NULL,
  batch_year SMALLINT NOT NULL REFERENCES public.batches(batch_year) ON UPDATE CASCADE,
  session TEXT NULL,
  academic_stream public.academic_stream_type NULL,
  academic_group VARCHAR(32) NULL,
  section VARCHAR(32) NULL,

  -- Server-controlled verification state
  verification_status public.verification_status NOT NULL DEFAULT 'unverified',
  verification_method public.verification_method NULL,
  vouches_count SMALLINT NOT NULL DEFAULT 0 CHECK (vouches_count >= 0),
  vouch_target_count SMALLINT NOT NULL DEFAULT 2 CHECK (vouch_target_count >= 1),
  verified_at TIMESTAMPTZ NULL,
  verified_by_profile_id BIGINT NULL REFERENCES public.alumni_profiles(id) ON DELETE SET NULL,

  -- Professional & academic directory attributes
  profession TEXT NOT NULL DEFAULT 'Not Specified',
  position TEXT NOT NULL DEFAULT '',
  institution TEXT NOT NULL DEFAULT '',
  cadre TEXT NULL,
  specialty TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  specialty_other TEXT NULL,
  degree TEXT[] NOT NULL DEFAULT '{"HSC"}'::TEXT[],

  -- Location & map directory coordinates
  city TEXT NOT NULL DEFAULT 'Dhaka',
  country TEXT NOT NULL DEFAULT 'Bangladesh',
  latitude DOUBLE PRECISION NULL CHECK (latitude IS NULL OR (latitude BETWEEN -90.0 AND 90.0)),
  longitude DOUBLE PRECISION NULL CHECK (longitude IS NULL OR (longitude BETWEEN -180.0 AND 180.0)),

  -- Profile narrative & badges
  bio TEXT NULL CHECK (bio IS NULL OR char_length(bio) <= 2500),
  career_history TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  badges TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  blood_group public.blood_group_type NULL,

  -- Sensitive / Private fields (column-level SELECT revoked from PUBLIC/anon/authenticated in 003)
  college_roll VARCHAR(32) NULL,
  email extensions.citext NULL UNIQUE,
  phone VARCHAR(32) NULL UNIQUE,
  whatsapp VARCHAR(32) NULL,
  fb_link TEXT NULL,

  -- Privacy & activity metadata
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  show_contact_to_verified BOOLEAN NOT NULL DEFAULT TRUE,
  posts_count INTEGER NOT NULL DEFAULT 0 CHECK (posts_count >= 0),
  last_seen_at TIMESTAMPTZ NULL DEFAULT now(),

  -- Full-Text Search generated column for 100,000+ scale directory search
  -- Excludes sensitive fields (email, phone, whatsapp, college_roll)
  search_vector TSVECTOR GENERATED ALWAYS AS (
    setweight(to_tsvector('simple', coalesce(full_name, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(institution, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(profession, '') || ' ' || coalesce(position, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(city, '') || ' ' || coalesce(country, '')), 'C')
  ) STORED,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_alumni_group_requires_stream
    CHECK (academic_group IS NULL OR academic_stream IS NOT NULL),
  CONSTRAINT fk_alumni_stream_group
    FOREIGN KEY (academic_stream, academic_group)
    REFERENCES public.academic_stream_groups (stream, group_code)
    MATCH SIMPLE
    ON UPDATE CASCADE
);

-- Link batches.representative_profile_id -> alumni_profiles.id now that alumni_profiles exists
DO $$ BEGIN
  ALTER TABLE public.batches
    ADD CONSTRAINT fk_batches_representative_profile
    FOREIGN KEY (representative_profile_id)
    REFERENCES public.alumni_profiles(id)
    ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 3.3 posts
CREATE TABLE IF NOT EXISTS public.posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id BIGINT NOT NULL REFERENCES public.alumni_profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL CHECK (char_length(trim(content)) BETWEEN 1 AND 10000),
  category public.post_category_type NOT NULL DEFAULT 'General Update',
  images TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  videos TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  likes_count INTEGER NOT NULL DEFAULT 0 CHECK (likes_count >= 0),
  comments_count INTEGER NOT NULL DEFAULT 0 CHECK (comments_count >= 0),
  is_edited BOOLEAN NOT NULL DEFAULT FALSE,
  is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3.4 post_comments
CREATE TABLE IF NOT EXISTS public.post_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  parent_comment_id BIGINT NULL REFERENCES public.post_comments(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES public.alumni_profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL CHECK (char_length(trim(content)) BETWEEN 1 AND 3000),
  likes_count INTEGER NOT NULL DEFAULT 0 CHECK (likes_count >= 0),
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3.5 post_likes
CREATE TABLE IF NOT EXISTS public.post_likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES public.alumni_profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_post_likes_post_user UNIQUE (post_id, user_id)
);

-- 3.6 saved_posts
CREATE TABLE IF NOT EXISTS public.saved_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.alumni_profiles(id) ON DELETE CASCADE,
  post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_saved_posts_user_post UNIQUE (user_id, post_id)
);

-- 3.7 admin_doc_submissions
-- Created prior to verification_requests so verification_requests can reference it cleanly.
-- storage_object_path stores the internal path inside the PRIVATE bucket `verification-documents`.
CREATE TABLE IF NOT EXISTS public.admin_doc_submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id BIGINT NOT NULL REFERENCES public.alumni_profiles(id) ON DELETE CASCADE,
  batch_year SMALLINT NOT NULL REFERENCES public.batches(batch_year),
  college_roll VARCHAR(32) NOT NULL,
  academic_stream public.academic_stream_type NOT NULL,
  academic_group VARCHAR(32) NULL,
  doc_type public.verification_doc_type NOT NULL,
  doc_type_label VARCHAR(128) NOT NULL,
  storage_object_path TEXT NOT NULL CHECK (char_length(trim(storage_object_path)) > 0),
  status public.request_review_status NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by BIGINT NULL REFERENCES public.alumni_profiles(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ NULL,
  admin_note TEXT NULL,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_admin_doc_no_self_review CHECK (reviewed_by IS NULL OR reviewed_by <> user_id),
  CONSTRAINT fk_admin_doc_stream_group
    FOREIGN KEY (academic_stream, academic_group)
    REFERENCES public.academic_stream_groups (stream, group_code)
    MATCH SIMPLE
    ON UPDATE CASCADE
);

-- 3.8 verification_requests
CREATE TABLE IF NOT EXISTS public.verification_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id BIGINT NOT NULL REFERENCES public.alumni_profiles(id) ON DELETE CASCADE,
  batch_year SMALLINT NOT NULL REFERENCES public.batches(batch_year),
  college_roll VARCHAR(32) NOT NULL,
  academic_stream public.academic_stream_type NOT NULL,
  academic_group VARCHAR(32) NULL,
  section VARCHAR(32) NULL,
  message TEXT NULL CHECK (message IS NULL OR char_length(message) <= 1000),
  status public.request_review_status NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'verified', 'declined')),
  target_vouches SMALLINT NOT NULL DEFAULT 2 CHECK (target_vouches >= 2),
  current_vouches SMALLINT NOT NULL DEFAULT 0 CHECK (current_vouches >= 0),
  id_doc_submission_id UUID NULL REFERENCES public.admin_doc_submissions(id) ON DELETE SET NULL,
  admin_note TEXT NULL,
  reviewed_by BIGINT NULL REFERENCES public.alumni_profiles(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_verification_req_no_self_review CHECK (reviewed_by IS NULL OR reviewed_by <> requester_id),
  CONSTRAINT fk_verification_req_stream_group
    FOREIGN KEY (academic_stream, academic_group)
    REFERENCES public.academic_stream_groups (stream, group_code)
    MATCH SIMPLE
    ON UPDATE CASCADE
);

-- 3.9 peer_vouches
CREATE TABLE IF NOT EXISTS public.peer_vouches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  verification_request_id UUID NOT NULL REFERENCES public.verification_requests(id) ON DELETE CASCADE,
  requester_id BIGINT NOT NULL REFERENCES public.alumni_profiles(id) ON DELETE CASCADE,
  voucher_id BIGINT NOT NULL REFERENCES public.alumni_profiles(id) ON DELETE CASCADE,
  voucher_batch SMALLINT NOT NULL REFERENCES public.batches(batch_year),
  comment TEXT NULL CHECK (comment IS NULL OR char_length(comment) <= 500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_peer_vouches_no_self_vouch CHECK (voucher_id <> requester_id),
  CONSTRAINT uq_peer_vouches_request_voucher UNIQUE (verification_request_id, voucher_id),
  CONSTRAINT uq_peer_vouches_requester_voucher UNIQUE (requester_id, voucher_id)
);

-- 3.10 blood_donors
CREATE TABLE IF NOT EXISTS public.blood_donors (
  user_id BIGINT PRIMARY KEY REFERENCES public.alumni_profiles(id) ON DELETE CASCADE,
  blood_group public.blood_group_type NOT NULL,
  is_registered_donor BOOLEAN NOT NULL DEFAULT TRUE,
  availability public.blood_donor_availability NOT NULL DEFAULT 'available',
  preferred_area TEXT NOT NULL,
  city TEXT NOT NULL DEFAULT 'Dhaka',
  last_donation_date DATE NULL,
  emergency_alert_preference public.blood_alert_preference NOT NULL DEFAULT 'all_urgent',
  donation_history JSONB NOT NULL DEFAULT '[]'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3.11 blood_requests
CREATE TABLE IF NOT EXISTS public.blood_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id BIGINT NOT NULL REFERENCES public.alumni_profiles(id) ON DELETE CASCADE,
  blood_group public.blood_group_type NOT NULL,
  units_required SMALLINT NOT NULL DEFAULT 1 CHECK (units_required BETWEEN 1 AND 20),
  units_fulfilled SMALLINT NOT NULL DEFAULT 0 CHECK (units_fulfilled >= 0),
  hospital_name TEXT NOT NULL CHECK (char_length(trim(hospital_name)) BETWEEN 2 AND 250),
  hospital_area TEXT NOT NULL,
  city TEXT NOT NULL DEFAULT 'Dhaka',
  required_datetime TIMESTAMPTZ NOT NULL,
  emergency_level public.blood_emergency_level NOT NULL DEFAULT 'urgent',
  contact_method public.blood_contact_method NOT NULL DEFAULT 'Portal Secure Coordination',
  coordination_ref VARCHAR(120) NULL,
  description TEXT NOT NULL CHECK (char_length(trim(description)) BETWEEN 5 AND 1500),
  patient_relation VARCHAR(120) NULL,
  status public.blood_request_status NOT NULL DEFAULT 'Active',
  moderation_note TEXT NULL,
  verified_by_admin_id BIGINT NULL REFERENCES public.alumni_profiles(id) ON DELETE SET NULL,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '72 hours'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3.12 blood_request_responses
CREATE TABLE IF NOT EXISTS public.blood_request_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  request_id UUID NOT NULL REFERENCES public.blood_requests(id) ON DELETE CASCADE,
  donor_user_id BIGINT NOT NULL REFERENCES public.alumni_profiles(id) ON DELETE CASCADE,
  status public.blood_response_status NOT NULL DEFAULT 'offered',
  note TEXT NULL CHECK (note IS NULL OR char_length(note) <= 500),
  responded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_blood_response_request_donor UNIQUE (request_id, donor_user_id)
);

-- 3.13 notifications
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id BIGINT NOT NULL REFERENCES public.alumni_profiles(id) ON DELETE CASCADE,
  actor_id BIGINT NULL REFERENCES public.alumni_profiles(id) ON DELETE SET NULL,
  type public.notification_type NOT NULL DEFAULT 'system',
  title TEXT NOT NULL CHECK (char_length(trim(title)) BETWEEN 1 AND 250),
  message TEXT NOT NULL CHECK (char_length(trim(message)) BETWEEN 1 AND 1500),
  unread BOOLEAN NOT NULL DEFAULT TRUE,
  target_route TEXT NULL,
  post_id BIGINT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  blood_request_id UUID NULL REFERENCES public.blood_requests(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3.14 gallery_albums
CREATE TABLE IF NOT EXISTS public.gallery_albums (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL CHECK (char_length(trim(title)) BETWEEN 2 AND 250),
  description TEXT NULL,
  category public.gallery_category_type NOT NULL DEFAULT 'campus',
  event_date_label VARCHAR(64) NOT NULL,
  location TEXT NULL,
  batch_year SMALLINT NULL REFERENCES public.batches(batch_year) ON DELETE SET NULL,
  cover_url TEXT NOT NULL,
  photos_count INTEGER NOT NULL DEFAULT 0 CHECK (photos_count >= 0),
  created_by_id BIGINT NULL REFERENCES public.alumni_profiles(id) ON DELETE SET NULL,
  is_published BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3.15 gallery_photos
CREATE TABLE IF NOT EXISTS public.gallery_photos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  album_id BIGINT NOT NULL REFERENCES public.gallery_albums(id) ON DELETE CASCADE,
  uploader_id BIGINT NULL REFERENCES public.alumni_profiles(id) ON DELETE SET NULL,
  url TEXT NOT NULL,
  storage_object_path TEXT NULL,
  caption TEXT NULL CHECK (caption IS NULL OR char_length(caption) <= 1000),
  batch_year SMALLINT NULL REFERENCES public.batches(batch_year) ON DELETE SET NULL,
  tags TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  media_type VARCHAR(16) NOT NULL DEFAULT 'image' CHECK (media_type IN ('image', 'video')),
  file_size VARCHAR(32) NULL,
  likes_count INTEGER NOT NULL DEFAULT 0 CHECK (likes_count >= 0),
  is_approved BOOLEAN NOT NULL DEFAULT TRUE,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3.16 official_notices
CREATE TABLE IF NOT EXISTS public.official_notices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ref_no VARCHAR(64) NOT NULL UNIQUE,
  title TEXT NOT NULL CHECK (char_length(trim(title)) BETWEEN 3 AND 300),
  category public.notice_category_type NOT NULL DEFAULT 'General',
  published_date DATE NOT NULL DEFAULT CURRENT_DATE,
  is_urgent BOOLEAN NOT NULL DEFAULT FALSE,
  summary TEXT NOT NULL,
  full_content TEXT NOT NULL,
  pdf_url TEXT NULL,
  file_size VARCHAR(32) NULL,
  signatory_name TEXT NOT NULL,
  signatory_designation TEXT NOT NULL,
  signatory_organization TEXT NOT NULL DEFAULT 'Notre Dame College Alumni Association',
  created_by BIGINT NULL REFERENCES public.alumni_profiles(id) ON DELETE SET NULL,
  is_published BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3.17 contact_inquiries
CREATE TABLE IF NOT EXISTS public.contact_inquiries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_profile_id BIGINT NULL REFERENCES public.alumni_profiles(id) ON DELETE SET NULL,
  name TEXT NOT NULL CHECK (char_length(trim(name)) BETWEEN 2 AND 120),
  batch_year SMALLINT NULL CHECK (batch_year IS NULL OR (batch_year BETWEEN 1 AND 150)),
  email extensions.citext NOT NULL,
  phone VARCHAR(32) NULL,
  subject VARCHAR(200) NOT NULL DEFAULT 'General Alumni Inquiry',
  message TEXT NOT NULL CHECK (char_length(trim(message)) BETWEEN 10 AND 5000),
  status VARCHAR(32) NOT NULL DEFAULT 'new'
    CHECK (status IN ('new', 'in_progress', 'resolved', 'archived')),
  handled_by BIGINT NULL REFERENCES public.alumni_profiles(id) ON DELETE SET NULL,
  admin_notes TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3.18 audit_logs
-- Append-only server audit log. Never stores passwords, tokens, secrets, or private document URLs.
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_profile_id BIGINT NULL REFERENCES public.alumni_profiles(id) ON DELETE SET NULL,
  actor_auth_id UUID NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  actor_role public.user_role NULL,
  action VARCHAR(120) NOT NULL,
  entity_table VARCHAR(64) NOT NULL,
  entity_id TEXT NOT NULL,
  old_values JSONB NULL,
  new_values JSONB NULL,
  reason TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 4. INDEXES FOR 100,000+ ALUMNI SCALE, CURSOR PAGINATION & FULL-TEXT SEARCH
-- -----------------------------------------------------------------------------

-- 4.1 batches indexes
CREATE INDEX IF NOT EXISTS idx_batches_hsc_year
  ON public.batches (hsc_year DESC)
  WHERE hsc_year IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_batches_rep_profile_id
  ON public.batches (representative_profile_id)
  WHERE representative_profile_id IS NOT NULL;

-- 4.2 alumni_profiles indexes (Keyset pagination, filters, FTS, trigram, geospatial)
CREATE UNIQUE INDEX IF NOT EXISTS uq_alumni_batch_college_roll
  ON public.alumni_profiles (batch_year, college_roll)
  WHERE college_roll IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_alumni_directory_cursor
  ON public.alumni_profiles (id DESC)
  WHERE is_public = TRUE;

CREATE INDEX IF NOT EXISTS idx_alumni_batch_cursor
  ON public.alumni_profiles (batch_year DESC, id DESC)
  WHERE is_public = TRUE;

CREATE INDEX IF NOT EXISTS idx_alumni_stream_group_cursor
  ON public.alumni_profiles (academic_stream, academic_group, batch_year DESC, id DESC)
  WHERE is_public = TRUE AND academic_stream IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_alumni_verification_cursor
  ON public.alumni_profiles (verification_status, batch_year DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_alumni_profession_cursor
  ON public.alumni_profiles (profession, id DESC)
  WHERE is_public = TRUE;

CREATE INDEX IF NOT EXISTS idx_alumni_country_city_cursor
  ON public.alumni_profiles (country, city, id DESC)
  WHERE is_public = TRUE;

CREATE INDEX IF NOT EXISTS idx_alumni_blood_group
  ON public.alumni_profiles (blood_group, city)
  WHERE blood_group IS NOT NULL AND is_public = TRUE;

CREATE INDEX IF NOT EXISTS idx_alumni_geo_coords
  ON public.alumni_profiles (latitude, longitude)
  WHERE is_public = TRUE AND latitude IS NOT NULL AND longitude IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_alumni_specialty_gin
  ON public.alumni_profiles USING GIN (specialty);

CREATE INDEX IF NOT EXISTS idx_alumni_degree_gin
  ON public.alumni_profiles USING GIN (degree);

CREATE INDEX IF NOT EXISTS idx_alumni_search_vector_gin
  ON public.alumni_profiles USING GIN (search_vector);

CREATE INDEX IF NOT EXISTS idx_alumni_full_name_trgm
  ON public.alumni_profiles USING GIN (full_name extensions.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_alumni_verified_by
  ON public.alumni_profiles (verified_by_profile_id)
  WHERE verified_by_profile_id IS NOT NULL;

-- 4.3 posts indexes (Cursor pagination & author/category feeds)
CREATE INDEX IF NOT EXISTS idx_posts_feed_cursor
  ON public.posts (is_pinned DESC, created_at DESC, id DESC)
  WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_posts_category_cursor
  ON public.posts (category, created_at DESC, id DESC)
  WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_posts_author_cursor
  ON public.posts (author_id, created_at DESC, id DESC)
  WHERE is_deleted = FALSE;

-- 4.4 post_comments indexes
CREATE INDEX IF NOT EXISTS idx_post_comments_post_cursor
  ON public.post_comments (post_id, created_at ASC, id ASC)
  WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_post_comments_parent
  ON public.post_comments (parent_comment_id)
  WHERE parent_comment_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_post_comments_user
  ON public.post_comments (user_id, created_at DESC);

-- 4.5 post_likes indexes
CREATE INDEX IF NOT EXISTS idx_post_likes_user_post
  ON public.post_likes (user_id, post_id);

-- 4.6 saved_posts indexes
CREATE INDEX IF NOT EXISTS idx_saved_posts_user_cursor
  ON public.saved_posts (user_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_saved_posts_post_id
  ON public.saved_posts (post_id);

-- 4.7 notifications indexes
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_cursor
  ON public.notifications (recipient_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient_unread
  ON public.notifications (recipient_id, created_at DESC)
  WHERE unread = TRUE;

CREATE INDEX IF NOT EXISTS idx_notifications_actor
  ON public.notifications (actor_id)
  WHERE actor_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_notifications_post_id
  ON public.notifications (post_id)
  WHERE post_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_notifications_blood_request_id
  ON public.notifications (blood_request_id)
  WHERE blood_request_id IS NOT NULL;

-- 4.8 verification_requests, peer_vouches & admin_doc_submissions indexes
CREATE UNIQUE INDEX IF NOT EXISTS uq_verification_req_active_requester
  ON public.verification_requests (requester_id)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_verification_req_batch_status
  ON public.verification_requests (batch_year, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_verification_req_status_created
  ON public.verification_requests (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_verification_req_doc_submission
  ON public.verification_requests (id_doc_submission_id)
  WHERE id_doc_submission_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_verification_req_reviewed_by
  ON public.verification_requests (reviewed_by)
  WHERE reviewed_by IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_peer_vouches_voucher
  ON public.peer_vouches (voucher_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_doc_status_submitted
  ON public.admin_doc_submissions (status, submitted_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_doc_user_id
  ON public.admin_doc_submissions (user_id, submitted_at DESC);

CREATE INDEX IF NOT EXISTS idx_admin_doc_reviewed_by
  ON public.admin_doc_submissions (reviewed_by)
  WHERE reviewed_by IS NOT NULL;

-- 4.9 blood network indexes
CREATE INDEX IF NOT EXISTS idx_blood_donors_matching
  ON public.blood_donors (blood_group, availability, city, preferred_area)
  WHERE is_registered_donor = TRUE;

CREATE INDEX IF NOT EXISTS idx_blood_requests_active_feed
  ON public.blood_requests (status, emergency_level, required_datetime ASC)
  WHERE status IN ('Pending Verification', 'Active', 'Donor Found');

CREATE INDEX IF NOT EXISTS idx_blood_requests_group_city
  ON public.blood_requests (blood_group, city, status);

CREATE INDEX IF NOT EXISTS idx_blood_requests_requester
  ON public.blood_requests (requester_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_blood_requests_verified_by_admin
  ON public.blood_requests (verified_by_admin_id)
  WHERE verified_by_admin_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_blood_responses_request
  ON public.blood_request_responses (request_id, responded_at ASC);

CREATE INDEX IF NOT EXISTS idx_blood_responses_donor
  ON public.blood_request_responses (donor_user_id, responded_at DESC);

-- 4.10 gallery, notices, inquiries & audit_logs indexes
CREATE INDEX IF NOT EXISTS idx_gallery_albums_category_created
  ON public.gallery_albums (category, created_at DESC)
  WHERE is_published = TRUE;

CREATE INDEX IF NOT EXISTS idx_gallery_albums_batch
  ON public.gallery_albums (batch_year, created_at DESC)
  WHERE batch_year IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gallery_albums_created_by
  ON public.gallery_albums (created_by_id)
  WHERE created_by_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gallery_photos_album_cursor
  ON public.gallery_photos (album_id, uploaded_at DESC, id)
  WHERE is_approved = TRUE;

CREATE INDEX IF NOT EXISTS idx_gallery_photos_uploader
  ON public.gallery_photos (uploader_id)
  WHERE uploader_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gallery_photos_batch
  ON public.gallery_photos (batch_year)
  WHERE batch_year IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_gallery_photos_tags_gin
  ON public.gallery_photos USING GIN (tags);

CREATE INDEX IF NOT EXISTS idx_official_notices_published
  ON public.official_notices (published_date DESC, is_urgent DESC)
  WHERE is_published = TRUE;

CREATE INDEX IF NOT EXISTS idx_official_notices_created_by
  ON public.official_notices (created_by)
  WHERE created_by IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_contact_inquiries_status_created
  ON public.contact_inquiries (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_contact_inquiries_sender
  ON public.contact_inquiries (sender_profile_id)
  WHERE sender_profile_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_contact_inquiries_handled_by
  ON public.contact_inquiries (handled_by)
  WHERE handled_by IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at
  ON public.audit_logs (created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor
  ON public.audit_logs (actor_profile_id, created_at DESC)
  WHERE actor_profile_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_auth
  ON public.audit_logs (actor_auth_id, created_at DESC)
  WHERE actor_auth_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity
  ON public.audit_logs (entity_table, entity_id, created_at DESC);

COMMIT;
